springdoc:
  swagger-ui.path: /swagger-ui
  packagesToScan: ru.simohin.mayflower.test.api
spring:
  application.name: mayflower-test
  h2:
    #    disable in prod
    console.enabled: true
    console:
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:${spring.application.name}
    username: ${spring.application.name}
    password: ${DB_PASSWORD:password}
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
payment.url:
  base: "http://localhost:8080"
  success: "/success"
  failure: "/failure"
integration:
  upgate:
    url: ${UPGATE_URL:https://sandbox.upgate.com/v1}
    key: ${UPGATE_KEY:1115b450-fa58-47d6-b94b-d25b9e948771}
feign:
  client:
    config:
      sale:
        loggerLevel: full
        decoder: feign.jackson.JacksonDecoder
        encoder: feign.jackson.JacksonEncoder
        requestInterceptors:
          - ru.simohin.mayflower.test.integration.upgate.client.interceptor.XApiKeyInterceptor